name: habitpunk
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.17.2
  firebase_storage: ^11.6.10
  intl: ^0.17.0 # Check for the latest version
  flutter_riverpod: ^2.4.9
  shared_preferences: ^2.0.15
  google_sign_in: ^6.2.1
  flutter_secure_storage: ^9.0.0
  firebase_messaging: ^14.9.1
  firebase_app_check: ^0.2.2+4
  cloud_firestore_web: ^3.12.2
  firebase_auth_web: ^5.11.4
  firebase_storage_web: ^3.9.4
  fl_chart: ^0.67.0
  table_calendar: ^3.0.5
  purchases_flutter: ^6.29.0
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/items/
    - assets/images/bosses/
    - assets/audio/

