// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWlvUHnwx4RB642D6ro7RWoNkzU2P94zs',
    appId: '1:566105220440:web:8473a8cececc662fa3b12d',
    messagingSenderId: '566105220440',
    projectId: 'projectfinal-f539b',
    authDomain: 'projectfinal-f539b.firebaseapp.com',
    storageBucket: 'projectfinal-f539b.appspot.com',
    measurementId: 'G-D1MJ86DNL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaVnxuGcXLBlh30KlVK1fCD7x3wY6AX2s',
    appId: '1:566105220440:android:1750f72801feca66a3b12d',
    messagingSenderId: '566105220440',
    projectId: 'projectfinal-f539b',
    storageBucket: 'projectfinal-f539b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcE7dHu3Y3P_koPVQeGt9D6zRzeSi7a1w',
    appId: '1:566105220440:ios:173b33f990501642a3b12d',
    messagingSenderId: '566105220440',
    projectId: 'projectfinal-f539b',
    storageBucket: 'projectfinal-f539b.appspot.com',
    iosClientId: '566105220440-rlimdrhugfkm8fhkrs4batljq1l9gh73.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitpunk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcE7dHu3Y3P_koPVQeGt9D6zRzeSi7a1w',
    appId: '1:566105220440:ios:bcc287689c3dcc25a3b12d',
    messagingSenderId: '566105220440',
    projectId: 'projectfinal-f539b',
    storageBucket: 'projectfinal-f539b.appspot.com',
    iosClientId: '566105220440-c7iao1oeuck7bakf1e3miv0t2d8t2tts.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitpunk.RunnerTests',
  );
}
